version: 2.1
orbs:
  node: circleci/node@4.2.1
  puppeteer: threetreeslight/puppeteer@0.1.2
jobs:
  build:
    docker:
      - image: circleci/node:latest-browsers
        environment:
          NODE_ENV: development
  test:
    executor:
      name: node/default
    steps:
      - checkout
      - node/install-packages
      - run: "npm run test:unit"
      - run: "npm run test:supertest"
      - run: "npm run test:e2e"
workflows:
  test_my_app:
    jobs:
      - build
      - test

