version: 2.1
orbs:
  node: circleci/node@<version??>
jobs:
  test:
    // test defined here
    executor:
      name: node/default
    steps:
      - checkout
      - node/install-packages
        - run: 
          command: npm run test:e2e
          command: npm run test:unit
          command: npm run test:supertest
workflows:
  test_my_app:
    jobs:
      - test
      
# version: 2.1
# orbs:
#   node: circleci/node@3.0.0
# workflows:
#   node-tests:
#     jobs:
#       - node/test

      
